export const userTypes = {
    SET_EMAIL_LOGIN: 'SET_EMAIL_LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',

    FORGOT_EMAIL_FAIL: 'FORGOT_EMAIL_FAIL',
    FORGOT_EMAIL_SUCCESS: 'FORGOT_EMAIL_SUCCESS',
    SET_EMAIL_FORGOTPASSWORD: 'SET_EMAIL_FORGOTPASSWORD',
    RESET_FORGOT_PASSWORD: 'RESET_FORGOT_PASSWORD',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_FAIL: 'VERIFY_OTP_FAIL',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_FAIL: 'FORGOT_PASSWORD_FAIL',
    RESET_IS_LOGIN: 'RESET_IS_LOGIN'
}
export const homeTypes = {
    SET_TOUR : 'SET_TOUR',
    SET_DISCOUNT_TOUR : 'SET_DISCOUNT_TOUR',
    SET_BLOG : 'SET_BLOG'
}
export const tourTypes = {
    SET_LOCATION : 'SET_LOCATION',
    SET_TOUR : 'SET_TOUR',
    SET_PAGE : 'SET_PAGE',
    SET_TOTAL_PAGE : 'SET_TOTAL_PAGE',
    RESET_TOUR : 'RESET_TOUR',
    SET_SEARCH_TEXT : 'SET_SEARCH_TEXT',
    SET_DATE_DEPART : 'SET_DATE_DEPART',
    SET_PROVINCE : 'SET_PROVINCE'
}

export const providerTypes = {
    SET_PROVIDER : 'SET_PROVIDER',
    SET_ALL_PROVIDER : 'SET_ALL_PROVIDER',
    SET_NAME_PROVIDER : 'SET_NAME_PROVIDER'
}

export const profileTypes = {
    SET_AUTH_LOGIN_SUCCESS: 'SET_AUTH_LOGIN_SUCCESS',
    SET_AUTH_LOGIN_FAIL: 'SET_AUTH_LOGIN_FAIL',

    UPDATE_INFOR_USER_SUCCESS: 'UPDATE_INFOR_USER_SUCCESS',
    UPDATE_INFOR_USER_FAIL: 'UPDATE_INFOR_USER_FAIL',
    RESET_PROFILE: 'RESET_PROFILE',
}

export const tourDetailTypes = {
    SET_TOUR_DETAIL : 'SET_TOUR_DETAIL',
    SET_TOUR_RELATED : 'SET_TOUR_RELATED'
}

export const bookingTypes = {
    SET_BOOKING : 'SET_BOOKING'
}